services:
  hometunes:
    container_name: hometunes
    restart: unless-stopped
    build:
      context: https://github.com/BuggyPasta/HomeTunes.git
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "12777:12777"
    volumes:
      - /home/user/docker_backup/hometunes:/data
      - /Music:/music:ro
    tmpfs:
      - /tmp
      - /var/run
      - /var/lib/nginx/body
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12777"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s