services:
  hometunes:
    container_name: hometunes
    restart: unless-stopped
    build:
      context: https://github.com/BuggyPasta/HomeTunes.git
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "12777:12777"
    volumes:
      - /home/user/docker_backup/hometunes:/data
    env_file:
      - ./.env
    security_opt:
      - no-new-privileges
    tmpfs:
      - /tmp
      - /var/run
      - /var/lib/nginx/body